# Generated by Django 5.0 on 2024-01-05 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizEndpoints', '0002_remove_users_quiz_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='quiz_ids',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
